### PR TITLE
Combine Data

### PR DESCRIPTION
**Pull request by sheilaikhwani**
I combined our table and it is succed.. Then I fixed the index. But there is conflict in our github. I'll try to fix it now.

### CODE REVIEW

**Comment by sheilaikhwani** [comment]
The conflict is resolved. You can check in there.

**Review by ranasahirasr — APPROVED** [review]
I think it's already done, Sheil. Thank you!

**Comment by ranasahirasr** [comment]
Thankyou, Sheila. I saw our file and it is succed

**Comment by sheilaikhwani** [comment]
Can you check our data in csv is there already in API data was combined?

**Comment by ranasahirasr** [comment]
Okay, i'll check it.

**Comment by sheilaikhwani** [comment]
Thankyou, Rana

**Pull request merged**
