### PR TITLE
Checking and Export Data

### PR DESCRIPTION
**Pull request by ranasahirasr**
@sheilaikhwani, I checked our data csv existing, it's already in API data was combined. But I think there is conflict in our github again, cab you fix it for me please?
Thankyou.

### CODE REVIEW

**Review by sheilaikhwani — APPROVED** [review]
There is conflict but I've done to fix it. Thankyou before, Rana.

**Comment by sheilaikhwani** [comment]
I've checked Rana and there is conflict. I've done to fix it and it's good now.

**Comment by ranasahirasr** [comment]
Btw, I think our task done and I've extracted our output to csv format

**Comment by sheilaikhwani** [comment]
Okay, Rana. Thankyou so much.
Very nice to work with you

**Pull request merged**
